indexing:
  data_dir: "data/covid"
  chroma_collection_name: "covid_baai"
  distance_fn: "ip"
  embedding_model: "BAAI/bge-base-en-v1.5"
  splitter_kwargs:
    chunk_size: 500
    chunk_overlap: 100

retrieval:
  query_file: "data/covid/dataset_with_ids.xlsx"
  k: 4

generating:
  model_name: "google/flan-t5-base"